// Must stay in sync with backend/src/config/crmEnums.js.
export const LEAD_STATUSES = ["NEW", "CONTACTED", "QUALIFIED", "UNQUALIFIED", "CONVERTED", "LOST"];
export const LEAD_SOURCES = ["WEBSITE", "WHATSAPP", "PHONE", "EMAIL", "REFERRAL", "SOCIAL_MEDIA", "ADVERTISEMENT", "DIRECT", "OTHER"];
export const PRIORITIES = ["LOW", "MEDIUM", "HIGH", "URGENT"];
export const CUSTOMER_STATUSES = ["PROSPECT", "ACTIVE", "INACTIVE"];
export const ENQUIRY_STATUSES = ["NEW", "IN_PROGRESS", "QUALIFIED", "PROPOSAL_REQUIRED", "CONVERTED", "CLOSED", "LOST"];

export const STATUS_COLORS = {
  NEW: "#1D4ED8", CONTACTED: "#0369A1", QUALIFIED: "#0F766E", UNQUALIFIED: "#6B7280",
  CONVERTED: "#166534", LOST: "#991B1B",
  IN_PROGRESS: "#B45309", PROPOSAL_REQUIRED: "#6D28D9", CLOSED: "#374151",
  PROSPECT: "#0369A1", ACTIVE: "#166534", INACTIVE: "#6B7280",
};

export const PRIORITY_COLORS = { LOW: "#6B7280", MEDIUM: "#0369A1", HIGH: "#B45309", URGENT: "#991B1B" };
